// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-qBd_MOdmS0fgUWlv_oxCj5KarBB2Wts',
    appId: '1:872077374684:web:806e0e198c1f190675f019',
    messagingSenderId: '872077374684',
    projectId: 'remote-config-cf2af',
    authDomain: 'remote-config-cf2af.firebaseapp.com',
    storageBucket: 'remote-config-cf2af.firebasestorage.app',
    measurementId: 'G-F93HZJXVYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBo6HdpswIruccLZEeyYEJKnwajvy0zw',
    appId: '1:872077374684:android:efeb8ee373da037f75f019',
    messagingSenderId: '872077374684',
    projectId: 'remote-config-cf2af',
    storageBucket: 'remote-config-cf2af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcDJcSE2prmYULuF6nGPGU90U-TriloMs',
    appId: '1:872077374684:ios:1e8d849cb298f03275f019',
    messagingSenderId: '872077374684',
    projectId: 'remote-config-cf2af',
    storageBucket: 'remote-config-cf2af.firebasestorage.app',
    iosBundleId: 'com.example.isSpam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcDJcSE2prmYULuF6nGPGU90U-TriloMs',
    appId: '1:872077374684:ios:1e8d849cb298f03275f019',
    messagingSenderId: '872077374684',
    projectId: 'remote-config-cf2af',
    storageBucket: 'remote-config-cf2af.firebasestorage.app',
    iosBundleId: 'com.example.isSpam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-qBd_MOdmS0fgUWlv_oxCj5KarBB2Wts',
    appId: '1:872077374684:web:a1185b1bb114b72e75f019',
    messagingSenderId: '872077374684',
    projectId: 'remote-config-cf2af',
    authDomain: 'remote-config-cf2af.firebaseapp.com',
    storageBucket: 'remote-config-cf2af.firebasestorage.app',
    measurementId: 'G-LQYK904B0P',
  );
}
